name: CI
on:
  push:
    branches: [master]
jobs:
  build-vx-debian:
    name: Build proxy package
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.4'
      - name: Build package
        run: make build-proxy-deb
  build-vx-tools-debian:
    name: Build tools package
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.4'
      - name: Build package
        run: make build-tools-deb
